Messenger/Models/ApplicationContext.cs
using Microsoft.EntityFrameworkCore;

namespace Messenger.Models
{
    public class ApplicationContext : DbContext
    {
        public DbSet<User> Users { get; set; } = null!;

        public DbSet<Dialog> Dialogs { get; set; } = null!;

        public DbSet<Message> Messages { get; set; } = null!;

        public ApplicationContext(DbContextOptions<ApplicationContext> options)
            : base(options)
        {
            Database.EnsureCreated();
        }
    }
}

Messenger/Models/Client.cs
namespace Messenger.Models
{
    // Упрощенная модель пользователя
    public class Client
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public Client(int id, string name)
        {
            Id = id;
            Name = name;
        }
    }
}

Messenger/Models/Dialog.cs
namespace Messenger.Models
{
    public class Dialog
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public Dialog(int id, string name)
        {
            Id = id;
            Name = name;
        }
    }
}

Messenger/Models/ErrorViewModel.cs
namespace Messenger.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Messenger/Models/Message.cs
namespace Messenger.Models
{
    public class Message
    {
        public int Id { get; set; }

        public string? Text { get; set; }

        public DateTime SendDate { get; set; }

        public int SenderId { get; set; }

        public User? Sender { get; set; }

        public int ReceiverId { get; set; }

        public User? Receiver { get; set; }

        public int DialogId { get; set; }

        public Dialog? Dialog { get; set; }
    }
}

Messenger/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace Messenger.Models
{
    public class User
    {
        public int Id { get; set; }

        public string? Name { get; set; }

        [Required]
        public string? Login { get; set; }

        [Required]
        public string? Password { get; set; }
    }
}

Messenger/Controllers/AuthorizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Messenger.Models;
using System.Text;
using System.Security.Cryptography;

namespace Messenger.Controllers
{
    public class AuthorizationController : Controller
    {
        ApplicationContext db;

        public AuthorizationController(ApplicationContext context)
        {
            db = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult NotExist()
        {
            return View("NotExist");
        }

        [HttpPost]
        public async Task<IActionResult> Index(string login, string password)
        {
            login = Hash(login);
            password = Hash(password);

            if (login != null && password != null)
            {
                User? user = await db.Users.FirstOrDefaultAsync(p => p.Login == login && p.Password == password);
                if (user != null)
                {
                    HttpContext.Response.Cookies.Append("User", $"{login} {password}");

                    return RedirectToAction("Index", "Main");
                }
            }

            return NotExist();
        }

        public string Hash(string data)
        {
            byte[] enc = Encoding.Default.GetBytes(data);
            SHA1 sha = new SHA1CryptoServiceProvider();
            byte[] result = sha.ComputeHash(enc);
            data = Convert.ToBase64String(result);
            return data;
        }
    }
}

Messenger/Controllers/HomeController.cs
using Messenger.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Messenger.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            HttpContext.Response.Cookies.Delete("User");

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Messenger/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Messenger.Models;

namespace Messenger.Controllers
{
    public class MainController : Controller
    {
        ApplicationContext db;
        User? _user;

        List<Message> _messages;


        public MainController(ApplicationContext context)
        {
            db = context;
        }

        public IActionResult Index()
        {
            if (HttpContext.Request.Cookies["User"] == null)
                return RedirectToAction("Index", "Home");

            // Получаем авторизованного пользователя
            GetUser();

            // Биндинг данных
            ViewData["User"] = _user.Name;

            _messages = (from m in db.Messages
                            where _user.Id == m.SenderId || _user.Id == m.ReceiverId
                            select m).ToList();
            ViewBag.Messages = _messages;


            var dialogs = (from m in _messages
                           select m.DialogId).ToList();
            ViewBag.Dialogs = dialogs.Distinct().ToList();

            ViewBag.FriendList = GetFriends();

            return View();
        }

        // Получить пользователя в системе
        public void GetUser()
        {
            var authString = HttpContext.Request.Cookies["User"];

            string[] dataList = authString.Split(' ');

            var login = dataList[0];
            var password = dataList[1];

            _user = db.Users.FirstOrDefault(p => p.Login == login && p.Password == password);
        }

        // Получить клиентов, с которыми есть диалоги
        List<Client> GetFriends()
        {
            var senderList = (from m in _messages
                              where _user.Id != m.SenderId
                              select m.SenderId).Distinct().ToList();

            var receiverList = (from m in _messages
                                where _user.Id != m.ReceiverId
                                select m.ReceiverId).Distinct().ToList();

            var friendsId = (senderList.Concat(receiverList)).Distinct();



            return (from u in GetAllUser()
                    from f in friendsId
                    where u.Id == f
                    select new Client(u.Id, u.Name)).ToList();
        }

        // Получить всех пользователей
        public List<User> GetAllUser()
        {
            return (from u in db.Users
                   select u).ToList();
        }
    }
}

Messenger/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Messenger.Models;
using System.Text;
using System.Security.Cryptography;

namespace Messenger.Controllers
{
    public class RegistrationController : Controller
    {
        ApplicationContext db;

        public RegistrationController(ApplicationContext context)
        {
            db = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult NotExist()
        {
            return View("NotExist");
        }

        [HttpPost]
        public async Task<IActionResult> Index(User user)
        {
            user.Login = Hash(user.Login);
            user.Password = Hash(user.Password);

            if (await db.Users.FirstOrDefaultAsync(p => p.Name == user.Name || p.Login == user.Login) == null)
            {
                db.Users.Add(user);
                await db.SaveChangesAsync();

                HttpContext.Response.Cookies.Append("User", $"{user.Login} {user.Password}");

                return RedirectToAction("Index", "Main");
            }
            return NotExist();
        }

        public string Hash(string data)
        {
            byte[] enc = Encoding.Default.GetBytes(data);
            SHA1 sha = new SHA1CryptoServiceProvider();
            byte[] result = sha.ComputeHash(enc);
            data = Convert.ToBase64String(result);
            return data;
        }
    }
}

Messenger/Views/Authorization/Index.cshtml
@model Messenger.Models.User

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/style.css">
    <title>Вход</title>
</head>
<body>
    <div class="container">
        <div id="form-container" class="form-container auth">
            <form asp-action="Index" asp-controller="Authorization" id="auth-form" class="form-container__form" method="post">
                <fieldset class="form-container__input-field">
                    <legend id="login-legend" class="form-container_fz">Логин</legend>
                    <input asp-for="Login" id="login" class="form-container__field" 
                        required 
                        pattern="^[a-zA-Z0-9][a-zA-Z0-9]{3,16}$"
                        minlength="4" maxlength="16" 
                        placeholder="Ваш логин" 
                        name="login"
                    >
                </fieldset>
                <fieldset class="form-container__input-field">
                    <legend id="password-legend" class="form-container_fz">Пароль</legend>
                    <input asp-for="Password" id="pass" class="form-container__field" 
                        required
                        type="password"
                        minlength="8" maxlength="24"
                        pattern="^[a-zA-Zа-яА-Я0-9][a-zA-Zа-яА-Я0-9]{7,24}$"
                        placeholder="Пароль" 
                        name="password"
                    >
                </fieldset>
                <div class="form-container__btn btn">
                    <a href="Registration" id="additional-button" class="btn__item">Создать аккаунт</a>
                    <input id="submit-button" class="btn__item" value="Вход" type="submit">
                </div>
            </form>
        </div>
    </div>

    <script src="../js/auth.js"></script>
</body>
</html>

Messenger/Views/Authorization/NotExist.cshtml
@model Messenger.Models.User

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/style.css">
    <title>Вход</title>
</head>
<body>
    <div class="container">
        <div id="form-container" class="form-container auth">
            <form asp-action="Index" asp-controller="Authorization" id="auth-form" class="form-container__form" method="post">
                <fieldset class="form-container__input-field">
                    <legend id="login-legend" class="form-container_fz error">Логин (Неверный логин или пароль)</legend>
                    <input asp-for="Login" id="login" class="form-container__field" 
                        required 
                        pattern="^[a-zA-Z0-9][a-zA-Z0-9]{3,16}$"
                        minlength="4" maxlength="16" 
                        placeholder="Ваш логин" 
                        name="login"
                    >
                </fieldset>
                <fieldset class="form-container__input-field">
                    <legend id="password-legend" class="form-container_fz">Пароль</legend>
                    <input asp-for="Password" id="pass" class="form-container__field" 
                        required
                        type="password"
                        minlength="8" maxlength="24"
                        pattern="^[a-zA-Zа-яА-Я0-9][a-zA-Zа-яА-Я0-9]{7,24}$"
                        placeholder="Пароль" 
                        name="password"
                    >
                </fieldset>
                <div class="form-container__btn btn">
                    <a href="Registration" id="additional-button" class="btn__item">Создать аккаунт</a>
                    <input id="submit-button" class="btn__item" value="Вход" type="submit">
                </div>
            </form>
        </div>
    </div>

    <script src="../js/auth.js"></script>
</body>
</html>

Messenger/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <title>Мессенджер</title>
</head>
<body>
    <div class="container">
        <div class="welcome-container">
            <div class="title">
                <p class="title__welcome">Добро пожаловать!</p>
                <p>Чтобы продолжить, войдите или зарегистрируйтесь</p>
            </div>
            <div class="auth-buttons">
                <a class="auth-buttons__btn" href="Authorization">Вход</a>
                <a class="auth-buttons__btn" href="Registration">Регистрация</a>
            </div>
        </div>
    </div>
</body>
</html>

Messenger/Views/Main/Index.cshtml
<!Doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link href="/css/main.css" rel="stylesheet">
    <title>Мессенджер</title>
  </head>
  <body>
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-12 col-md-4 d-md-block friend-m " id="friendMenu">
                    <div class="pt input-group dropdown mb-3 search">
                        <input id="searchBox" type="search" class="form-control border-bottom border-2 border-primary" placeholder="Найти собеседника:" aria-label="Search"
                          aria-describedby="search-addon" />
                        <button class="btn  border-0 dropdown-toggle-split" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false" data-bs-reference="parent">
                          <img src="img/search.png" width="20" height="20" alt="Найти"/>
                        </button>
                        <div id="findList" class="dropdown-menu dropdown-menu-dark w-100" aria-labelledby="dropdownMenu2">
                          <a id="findUser" class="dropdown-item" href="#">Ничего не найдено</a>
                         </div>
                      </div>
                      <div class="friend-win d-flex flex-column" id="dialog">
                        @if (@ViewBag.Dialogs.Count == 0)
                        {
                            <div class="cont" id="subtext">
                              <p class="mb f-text text-w">Нет созданных</p>
                              <p class="f-text text-w">диалогов</p>
                            </div>
                        } 
                        else
                        {
                            @foreach (var friend in @ViewBag.FriendList) 
                            {
                                <div class="card userCard text-white bg-dark shadow">
                                  <div class="card-body rey">
                                    <h5 class="card-title">@friend.Name</h5>
                                  </div>
                                </div>
                            }
                        }
                      </div>
                      <div class="user-info border-top border-2 border-primary">
                          <div class="row g-0 info-btn">
                            <div id="username" class="col-10 col-md-9 user-name text-w">@ViewData["User"]</div>
                            <div class="col-1 col-md-1 exit-btn-cont ">
                              <a href="Home" class="btn exit-btn">
                                  <img src="/img/exit.png" width="30" height="30" alt="Выйти"/>
                              </a>
                            </div>
                          </div>  
                      </div>
                </div>
                <div class="col-12 col-md-8 d-none d-md-block chat-win" id="chatWin">
                  <div class="subt" id="subtextWin">
                    <p class="title-text text-w">Добро пожаловать!</p>
                    <p class="t-text text-w">Найдите себе собеседника</p>
                  </div>
                  <div class="dialog-win d-none" id="DialogWin">
                    <div class="row">
                      <div class="col-12 col-md-12 dialog-head border-2 border-bottom border-primary">
                        <div class="row">
                          <button class="col-1 d-md-none  btn backArrow" id="backBtn">
                            <img src="img/left.png" width="30" height="30" alt="Назад">
                          </button>
                          <label class="col-10 col-md-12 text dialogName align-middle" id="dialog-info"></label>
                        </div>
                      </div>
                      <div class="col-12 col-md-12 dialog-body">
                        <div id="messengeWin" class="MessagesWin d-flex flex-column"></div>
                      </div>
                      <div class="col-12 col-md-12 border-2 border-top border-primary">
                        <div class="container footChat">
                          <div class="row contforInp">
                            <div class="col-9 col-md-10 contText">
                              <textarea class="form-control textdialog" placeholder="Введите сообщение:" id="usertext" rows="3"></textarea>
                            </div>
                            <div class="col-3 col-md-2 ">
                              <button class="btn" id="sendMessange"> 
                                <img src="/img/send.png" width="30" height="30" alt="Отправить"/>
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
        </div>
    <script src="/js/signalr/dist/browser/signalr.min.js"></script>
    <script src="/js/main.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </body>
</html>

@*
   @foreach (var dialogId in @ViewBag.Dialogs) 
   {
        <p>Id диалога: @dialogId</p>
        @foreach (var message in @ViewBag.Messages)
        {
        	if (@message.DialogId == @dialogId)
        	{
        		<p>@message.Text</p>
        	}
        }
   }
*@

@*
    @foreach (var message in @ViewBag.Messages)
    {
        <div class="card mb-3 text-white senderBox bg-transp">
            <div class="card-body reqsforChat">
                <div class="card-text text-white text-start">@message.Text</div>
                <div class="label text-end labelData small">@message.SendDate.ToShortTimeString()</div>
            </div>
        </div>
    }
*@

Messenger/Views/Shared/_Layout.cshtml
@RenderBody()